server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=MySQL
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  
  #devtool      
  devtools:
    livereload:
      enabled: true